
language: cpp

compiler: gcc

cache:
  - apt
  - ccache

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libarpack2-dev
      - libsuperlu-dev
      - libsuitesparse-dev
    update: true
  homebrew:
    packages:
      - arpack
      - superlu
      - suite-sparse
    update: true

env:
  - SUPERLU=ON BLAS=SYSTEM CHOLMOD=ON UMFPACK=ON

before_script:
  #- if [ "$TRAVIS_OS_NAME" = "linux" -a "$SUPERLU" = "ON" ]; then ./install-superlu.sh ; fi
  #- if [ "$CHOLMOD" = "ON" -o "$UMFPACK" = "ON" ]; then ./install-suitesparse.sh ; fi
  #- if [[ ( "$TRAVIS_OS_NAME" = "linux" ) && ( "$CHOLMOD" = "ON" || "$UMFPACK" = "ON" ) ]]; then ./install-suitesparse.sh ; fi

script:
  - cmake -B build -DENABLE_SUPERLU=$SUPERLU -DENABLE_UMFPACK=$UMFPACK -DENABLE_CHOLMOD=$CHOLMOD
  - cmake --build build --parallel
  - cmake --install build --prefix $PWD/install
#  - ctest --test-dir build --output-on-failure
